language: python
python:
  - "2.7"
# command to install dependencies
addons:
  firefox: "40.0"
install:
  - "pip install selenium"
  - "pip list"
script: python selenium.py
notifications:
  email: false
