language: python
python:
  - "2.7"
# command to install dependencies
addons:
  firefox: "40.0"
install:
  - "pip install selenium==2.40.0"
  - "pip list"
  - sleep 3
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
script: python selenium.py
notifications:
  email: false
