language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
# command to install dependencies
install: "pip install -r requirements.txt"
addons:
  firefox: "49.0"
script: selenium.py
notifications:
  email: false
