language: ruby
ruby:
  - "3.0"
# command to install dependencies
addons:
  firefox: "40.0"
install:
  - "gem install selenium-webdriver"
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
script: ruby selenium.rb
notifications:
  email: false
