language: ruby
rvm:
  - 2.2
after_success:
  - eval "$(ssh-agent -s)" #start the ssh agent
  - chmod 600 .travis/deploy_key.pem # this key should have push access
  - ssh-add .travis/deploy_key.pem
  - git remote add deploy 
  - git push deploy https://github.com/tjgadm/selenium_test/deploy/
script: ruby selenium.rb
notifications:
  email: false
